services:
  bot:
    build:
      context: .
    container_name: chat_summarizer_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./chat_summarizer.db:/app/chat_summarizer.db

networks:
  default:
    name: chat_summarizer_network
